export const MOCK_JOBS = [
  {
    id: 'job-1',
    job_number: 'JOB-2026-0001',
    title: 'Renovering af badeværelse',
    customer: {
      name: 'Familien Hansen',
      address: 'Vestergade 12, 2100 København Ø',
      customer_type: 'private',
    },
    status: 'sent',
    vat_handling: 'incl',
    total_price_excl_vat: 42800,
    rooms_count: 2,
    share_token: 'share-hansen-0001',
    assigned_to: 'Mikkel Montør',
    updated_at: '2026-04-21T10:30:00Z',
  },
  {
    id: 'job-2',
    job_number: 'JOB-2026-0002',
    title: 'Nyt køkken + bryggers',
    customer: {
      name: 'Café Linde ApS',
      address: 'Havnegade 3, 1058 København K',
      customer_type: 'business',
    },
    status: 'draft',
    vat_handling: 'excl',
    total_price_excl_vat: 89400,
    rooms_count: 2,
    share_token: 'share-linde-0002',
    assigned_to: 'Mikkel Montør',
    updated_at: '2026-04-22T14:15:00Z',
  },
  {
    id: 'job-3',
    job_number: 'JOB-2026-0003',
    title: 'Udskiftning af varmtvandsbeholder',
    customer: {
      name: 'Jens Petersen',
      address: 'Skovvej 48, 2860 Søborg',
      customer_type: 'private',
    },
    status: 'approved',
    vat_handling: 'incl',
    total_price_excl_vat: 14200,
    rooms_count: 1,
    share_token: 'share-petersen-0003',
    assigned_to: 'Mikkel Montør',
    updated_at: '2026-04-20T08:45:00Z',
  },
]

export const STATUS_LABELS = {
  draft: {
    label: 'Kladde',
    color: 'bg-rose-100 text-rose-800',
    border: 'border-rose-400',
    accent: 'bg-rose-500',
    chipActive: 'bg-rose-500 text-white border-rose-500',
  },
  sent: {
    label: 'Sendt til kunde',
    color: 'bg-amber-100 text-amber-800',
    border: 'border-amber-400',
    accent: 'bg-amber-500',
    chipActive: 'bg-amber-500 text-white border-amber-500',
  },
  approved: {
    label: 'Godkendt',
    color: 'bg-emerald-100 text-emerald-800',
    border: 'border-emerald-500',
    accent: 'bg-emerald-500',
    chipActive: 'bg-emerald-500 text-white border-emerald-500',
  },
  rejected: {
    label: 'Afvist',
    color: 'bg-sky-100 text-sky-800',
    border: 'border-sky-400',
    accent: 'bg-sky-500',
    chipActive: 'bg-sky-500 text-white border-sky-500',
  },
  in_progress: {
    label: 'I gang',
    color: 'bg-indigo-100 text-indigo-800',
    border: 'border-indigo-400',
    accent: 'bg-indigo-500',
    chipActive: 'bg-indigo-500 text-white border-indigo-500',
  },
  done: {
    label: 'Færdig',
    color: 'bg-slate-200 text-slate-700',
    border: 'border-slate-300',
    accent: 'bg-slate-500',
    chipActive: 'bg-slate-600 text-white border-slate-600',
  },
}
